### ISSUE TITLE
Swap links https://maddevs.io/careers/

### ISSUE THREAD

**Issue by maerkina** [maddevsio/maddevs#1191]
Swap 'HeadHunter' and 'Habr.com' links in https://maddevs.io/careers/

**Comment by denisoed** [comment]
@maerkina thank you for your feedback :)

The bug has been eliminated as part of this [PR](https://github.com/maddevsio/maddevs/pull/1193).

**Comment by denisoed** [comment]
[Fixed and Tested](https://maddevs.io/careers/)
